Running: python ui_test_suite.py with hidden params
In: /usr/local/google/home/eholder/workspaces/flask/ufo-management-server-flask/tests/ui/

No recaptcha site or secret key found. Please configure RECAPTCHA_SITE_KEY and RECAPTCHA_SECRET_KEY in the environment variables.
....E.......E...................
======================================================================
ERROR: testErrorNotificationIsWorking (error_notification_test.ErrorNotificationTest)
Test the error notification is properly wired up, opened, and closed.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/google/home/eholder/workspaces/flask/ufo-management-server-flask/tests/ui/error_notification_test.py", line 30, in tearDown
    should_raise_exception=False)
  File "/usr/local/google/home/eholder/workspaces/flask/ufo-management-server-flask/tests/ui/landing_page.py", line 63, in remove_test_user
    user_item.click()
  File "/usr/local/google/home/eholder/workspaces/flask/ufo-management-server-flask/venv/local/lib/python2.7/site-packages/selenium/webdriver/remote/webelement.py", line 75, in click
    self._execute(Command.CLICK_ELEMENT)
  File "/usr/local/google/home/eholder/workspaces/flask/ufo-management-server-flask/venv/local/lib/python2.7/site-packages/selenium/webdriver/remote/webelement.py", line 454, in _execute
    return self._parent.execute(command, params)
  File "/usr/local/google/home/eholder/workspaces/flask/ufo-management-server-flask/venv/local/lib/python2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 201, in execute
    self.error_handler.check_response(response)
  File "/usr/local/google/home/eholder/workspaces/flask/ufo-management-server-flask/venv/local/lib/python2.7/site-packages/selenium/webdriver/remote/errorhandler.py", line 188, in check_response
    raise exception_class(message, screen, stacktrace)
WebDriverException: Message: 


======================================================================
ERROR: testEditServer (landing_page_test.LandingPageTest)
Test that editing a server displays the modified server.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/google/home/eholder/workspaces/flask/ufo-management-server-flask/tests/ui/landing_page_test.py", line 187, in testEditServer
    self.args.server_url)
  File "/usr/local/google/home/eholder/workspaces/flask/ufo-management-server-flask/tests/ui/landing_page.py", line 113, in add_test_server
    host_public_key)
  File "/usr/local/google/home/eholder/workspaces/flask/ufo-management-server-flask/tests/ui/server_form.py", line 33, in addServer
    submit_button.click()
  File "/usr/local/google/home/eholder/workspaces/flask/ufo-management-server-flask/venv/local/lib/python2.7/site-packages/selenium/webdriver/remote/webelement.py", line 75, in click
    self._execute(Command.CLICK_ELEMENT)
  File "/usr/local/google/home/eholder/workspaces/flask/ufo-management-server-flask/venv/local/lib/python2.7/site-packages/selenium/webdriver/remote/webelement.py", line 454, in _execute
    return self._parent.execute(command, params)
  File "/usr/local/google/home/eholder/workspaces/flask/ufo-management-server-flask/venv/local/lib/python2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 201, in execute
    self.error_handler.check_response(response)
  File "/usr/local/google/home/eholder/workspaces/flask/ufo-management-server-flask/venv/local/lib/python2.7/site-packages/selenium/webdriver/remote/errorhandler.py", line 188, in check_response
    raise exception_class(message, screen, stacktrace)
WebDriverException: Message: 


----------------------------------------------------------------------
Ran 32 tests in 710.393s

FAILED (errors=2)
